import { apiClient } from '@/lib/api/client'
import {
  toJobLogEntries,
  toJobSummary,
  toProjectResultSummary,
  toResultDownloadItems,
} from '@/lib/api/mappers'
import { buildBackendUrl, resolveJobApiBaseUrl } from '@/lib/api/config'
import type {
  ApiJobArtifactsResponse,
  ApiJobListResponse,
  ApiJobLogsResponse,
  ApiJobRecord,
  ApiJobResultSummary,
} from '@/types/api'
import {
  type CreateTranslationJobInput,
  type JobLogEntry,
  type JobSummary,
  type ProjectDetailResource,
  type ProjectResultSummary,
  type ResultDownloadItem,
} from '@/types/jobs'

export interface JobListPage {
  jobs: JobSummary[]
  total: number
  limit: number | null
  offset: number
  hasMore: boolean
}

export interface ListJobsOptions {
  limit?: number
  offset?: number
}

export async function listJobsPage(options: ListJobsOptions = {}): Promise<JobListPage> {
  const params = new URLSearchParams()
  if (typeof options.limit === 'number') params.set('limit', String(options.limit))
  if (typeof options.offset === 'number') params.set('offset', String(options.offset))
  const suffix = params.toString()
  const payload = await apiClient.get<ApiJobListResponse>(`/jobs${suffix ? `?${suffix}` : ''}`)
  const jobs = payload.jobs.map(toJobSummary)
  const total = typeof payload.total === 'number' ? payload.total : jobs.length
  const offset = typeof payload.offset === 'number' ? payload.offset : (options.offset ?? 0)
  const limit =
    typeof payload.limit === 'number' || payload.limit === null
      ? payload.limit
      : (options.limit ?? null)
  const hasMore =
    typeof payload.has_more === 'boolean'
      ? payload.has_more
      : offset + jobs.length < total

  return { jobs, total, limit, offset, hasMore }
}

export async function listJobs(): Promise<JobSummary[]> {
  const page = await listJobsPage()
  return page.jobs
}

export async function getJob(jobId: string): Promise<JobSummary> {
  const payload = await apiClient.get<ApiJobRecord>(`/jobs/${jobId}`)
  return toJobSummary(payload)
}

export async function submitTranslationJob(
  input: CreateTranslationJobInput,
): Promise<JobSummary> {
  // When a local upload is in play, pass the original filename alongside
  // the sanitised upload path. The gateway's display_name orchestrator
  // truncates it into a friendly task title (plan §6.2 branch 3).
  const sourceType = input.sourceType ?? 'youtube_url'
  const source: Record<string, string> = {
    type: sourceType,
    value: sourceType === 'local_video' ? (input.localFilePath ?? '') : input.youtubeUrl,
  }
  if (sourceType === 'local_video' && input.localFileName) {
    source.filename = input.localFileName
  }

  const requestBody: Record<string, unknown> = {
    job_type: 'localize_video',
    output_target: 'editor',
    source,
    speakers: input.speakers,
    voice_a: input.voiceA,
    voice_b: input.voiceB,
    transcription_method: input.transcriptionMethod ?? 'assemblyai',
    service_mode: input.service_mode ?? 'express',
  }
  // Smart MVP master plan §5.3 (hardened Codex 第四十轮 P1.1):
  // smart submissions MUST carry the complete 6-field consent
  // payload. Gateway's validate_smart_consent() rejects partial
  // / malformed shapes with 400 ``smart_consent_invalid``. User
  // selects smart via the UI mode picker; clicking that button is
  // the implicit consent for all 6 fields (terms shown in the
  // smart card description). MVP defaults:
  //   - auto_voice_clone=true: MVP cloning is core value-add
  //   - auto_retranslate=false: MVP doesn't re-translate (deferred to P3+ verifier)
  //   - auto_retts=true: MVP retries failed TTS within budget
  //   - auto_multimodal_verification=false: verifier is P3+ feature
  //   - no_extra_charge_without_confirmation=true: fixed-price product promise
  //   - on_budget_exhausted=degraded_delivery_with_report:
  //     'fail_and_refund' is currently rejected by validator (partial-
  //     capture settle path is STUB; Codex 40 P1.2).
  if (requestBody.service_mode === 'smart') {
    requestBody.smart_consent = {
      auto_voice_clone: true,
      auto_retranslate: false,
      auto_retts: true,
      auto_multimodal_verification: false,
      no_extra_charge_without_confirmation: true,
      on_budget_exhausted: 'degraded_delivery_with_report',
    }
  }
  // Phase 4.3a PR3 — Express auto-clone consent. ALWAYS send express_consent
  // for express submissions (even when unchecked → auto_voice_clone:false), so
  // the backend never has to disambiguate "user declined" from "frontend bug
  // dropped the field" (spec §2.1). Only sent for express (smart has its own
  // smart_consent; studio sends neither). The value is read from the input
  // flag, which the form forces to false for non-express modes (spec §2.6), so
  // a stale checkbox can't trigger a paid clone. We send only auto_voice_clone +
  // client_confirmed_at; the server-side authoritative confirmation timestamp is
  // generated by the gateway alone and must never originate from the client.
  if (requestBody.service_mode === 'express') {
    const optedIn = input.expressAutoVoiceClone === true
    requestBody.express_consent = {
      auto_voice_clone: optedIn,
      client_confirmed_at: optedIn ? new Date().toISOString() : null,
    }
  }
  const payload = await apiClient.post<ApiJobRecord>('/jobs', {
    body: requestBody,
  })

  return toJobSummary(payload)
}

export async function continueJob(jobId: string): Promise<JobSummary> {
  const payload = await apiClient.post<ApiJobRecord>(`/jobs/${jobId}/continue`, {
    body: {},
  })
  return toJobSummary(payload)
}

/**
 * Rename a job's user-visible title. Hits the gateway's rename endpoint
 * (``PATCH /gateway/jobs/{id}``) which handles ownership + collision
 * resolution (plan §6.5 / D16). Empty / whitespace-only values are
 * rejected on the server with 400 — callers should validate client-side
 * before calling.
 *
 * ⚠ This endpoint lives at the raw ``/gateway/*`` path, not under the
 * client's default ``/job-api`` base. We use ``fetch`` directly here so
 * the apiClient's prefix assumption doesn't get in the way.
 */
export async function renameJob(jobId: string, displayName: string): Promise<JobSummary> {
  const response = await fetch(`/gateway/jobs/${jobId}`, {
    method: 'PATCH',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ display_name: displayName }),
  })
  if (!response.ok) {
    const errorBody = await response.json().catch(() => ({}))
    const message = errorBody?.message ?? errorBody?.detail ?? `重命名失败（HTTP ${response.status}）`
    throw new Error(message)
  }
  const payload = (await response.json()) as ApiJobRecord
  return toJobSummary(payload)
}

export async function getJobLogs(jobId: string): Promise<JobLogEntry[]> {
  const payload = await apiClient.get<ApiJobLogsResponse>(`/jobs/${jobId}/logs`)
  return toJobLogEntries(payload.events)
}

export async function getProjectResultSummary(
  jobId: string,
): Promise<ProjectResultSummary> {
  const payload = await apiClient.get<ApiJobResultSummary>(
    `/jobs/${jobId}/result-summary`,
  )
  return toProjectResultSummary(payload)
}

export async function getProjectArtifacts(
  jobId: string,
): Promise<ResultDownloadItem[]> {
  const payload = await apiClient.get<ApiJobArtifactsResponse>(
    `/jobs/${jobId}/artifacts`,
  )
  return toResultDownloadItems(payload)
}

export async function getProjectDetail(
  jobId: string,
): Promise<ProjectDetailResource> {
  const [job, result] = await Promise.all([
    getJob(jobId),
    getProjectResultSummary(jobId),
  ])
  let downloads: ResultDownloadItem[] = []
  try {
    downloads = await getProjectArtifacts(jobId)
  } catch {
    downloads = []
  }

  return {
    downloads,
    job,
    result,
  }
}

// ---------------------------------------------------------------------------
// Jianying draft on-demand generation (plan §11, K7+K8)
// ---------------------------------------------------------------------------

/**
 * Response for GET /job-api/jobs/{id}/jianying-draft-status
 * Polling shape — all timestamps ISO 8601 UTC or null.
 */
export interface JianyingDraftStatusResponse {
  status: 'idle' | 'running' | 'succeeded' | 'failed'
  started_at: string | null
  completed_at: string | null
  error: string | null
  draft_zip_path: string | null
  draft_zip_size_bytes: number | null
  artifact_key: 'editor.jianying_draft_zip' | null
}

/**
 * Response for POST /job-api/jobs/{id}/generate-jianying-draft
 * Server accepts (202) or returns existing succeeded state (200).
 */
export interface GenerateJianyingDraftResponse {
  status: 'running' | 'succeeded'
  started_at?: string
  completed_at?: string
  draft_zip_path?: string
  artifact_key?: string
  message?: string
}

/**
 * Trigger on-demand jianying draft generation.
 *
 * - idle / failed → 202, {status: "running"}
 * - already succeeded → 200, {status: "succeeded", artifact_key: ...}
 * - already running → 409 (throws ApiError)
 * - service_mode not studio → 403 (throws ApiError)
 * - invalid user_draft_root → 400 (throws Error with backend message)
 *
 * Pass `options.userDraftRoot` to tell the backend which local Jianying
 * drafts directory to bake absolute paths into (K11/K12/K13).
 */
export async function generateJianyingDraft(
  jobId: string,
  options?: { userDraftRoot?: string },
): Promise<GenerateJianyingDraftResponse> {
  const url = buildBackendUrl(resolveJobApiBaseUrl(), `/jobs/${jobId}/generate-jianying-draft`)
  const bodyPayload: Record<string, string> = {}
  if (options?.userDraftRoot) {
    bodyPayload.user_draft_root = options.userDraftRoot
  }
  const res = await fetch(url, {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(bodyPayload),
  })
  if (!res.ok) {
    const body = await res.json().catch(() => ({})) as Record<string, unknown>
    const message =
      typeof body.message === 'string' ? body.message :
      typeof body.detail === 'string' ? body.detail :
      `HTTP ${res.status}`
    throw new Error(message)
  }
  return res.json() as Promise<GenerateJianyingDraftResponse>
}

/**
 * Poll jianying draft status.
 * Returns the current state of jianying_draft_* fields on the job.
 */
export async function getJianyingDraftStatus(
  jobId: string,
): Promise<JianyingDraftStatusResponse> {
  const url = buildBackendUrl(resolveJobApiBaseUrl(), `/jobs/${jobId}/jianying-draft-status`)
  const res = await fetch(url, { credentials: 'include' })
  if (!res.ok) {
    throw new Error(`HTTP ${res.status}`)
  }
  return res.json() as Promise<JianyingDraftStatusResponse>
}

// =========================================================================
// PR#3C-P3-c: smart quality report (user-facing SmartAutoDecisionPanel)
// =========================================================================

import type { SmartQualityReport } from '@/types/smart'

/**
 * Discriminated-union result so the renderer can branch on shape without
 * try/catch — 404 service_mode_not_smart is the "hide the panel" signal,
 * 404 quality_report_not_written is the "smart job paused or in flight"
 * signal, and a thrown error is for unexpected 5xx / network failure.
 */
export type SmartQualityReportResult =
  | { kind: 'ok'; report: SmartQualityReport }
  | { kind: 'not_smart' }
  | { kind: 'not_written' }
  | { kind: 'not_found' }  // unknown job

/**
 * Fetch smart_quality_report.json via Job API. Per decision log §3 the
 * endpoint reads ONLY the quality_report sidecar — no cost data leaks
 * to the user-facing path.
 */
export async function getSmartQualityReport(
  jobId: string,
): Promise<SmartQualityReportResult> {
  const url = buildBackendUrl(
    resolveJobApiBaseUrl(),
    `/jobs/${jobId}/smart-quality-report`,
  )
  const res = await fetch(url, { credentials: 'include' })
  if (res.ok) {
    const report = (await res.json()) as SmartQualityReport
    return { kind: 'ok', report }
  }
  if (res.status === 404) {
    let errorCode: string | null = null
    try {
      const body = (await res.json()) as { error?: string }
      errorCode = body?.error ?? null
    } catch {
      // body not JSON — fall through to not_found
    }
    if (errorCode === 'service_mode_not_smart') return { kind: 'not_smart' }
    if (errorCode === 'quality_report_not_written') return { kind: 'not_written' }
    return { kind: 'not_found' }
  }
  throw new Error(`smart_quality_report fetch failed: HTTP ${res.status}`)
}

