#!/usr/bin/env python3
"""Import CosyVoice endpoint availability into voice_catalog.provider_config.

Reads the INTL_AVAILABLE_VOICES frozenset from cosyvoice_endpoint_config.py
and updates each CosyVoice voice's provider_config.endpoint_modes in the DB.

Usage (in gateway container or locally with DB access):
    python gateway/scripts/import_cosyvoice_endpoint_modes.py

Or generate SQL:
    python gateway/scripts/import_cosyvoice_endpoint_modes.py --sql
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Add src/ to path so we can import cosyvoice modules
_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(_ROOT / "src"))

# The 10 voices confirmed available on the international endpoint (2026-03-30 audit)
INTL_AVAILABLE_VOICES = frozenset([
    "longanyang", "longanhuan", "longhuhu_v3", "longanzhi_v3",
    "longanwen_v3", "longanyun_v3", "longanlang_v3",
    "longjiqi_v3", "longlaobo_v3", "longlaoyi_v3",
])

# All CosyVoice voice IDs from the catalog
try:
    from services.tts.cosyvoice_voice_catalog import _COSYVOICE_V3_FLASH_VOICES
    ALL_COSYVOICE_VOICE_IDS = [str(v["voice_id"]) for v in _COSYVOICE_V3_FLASH_VOICES]
except ImportError:
    # Fallback: we know there are 68 voices, but without the import we can't enumerate
    ALL_COSYVOICE_VOICE_IDS = []


def compute_endpoint_modes(voice_id: str) -> list[str]:
    """Determine which endpoint modes a voice supports."""
    modes = ["mainland"]  # All matchable voices work on mainland
    if voice_id in INTL_AVAILABLE_VOICES:
        modes.append("international")
    return modes


def generate_sql() -> str:
    """Generate SQL to update provider_config for all CosyVoice voices."""
    lines = [
        "-- Update CosyVoice voice_catalog entries with endpoint_modes",
        "-- Generated by import_cosyvoice_endpoint_modes.py",
        "BEGIN;",
        "",
    ]

    if not ALL_COSYVOICE_VOICE_IDS:
        # Fallback: update using INTL_AVAILABLE_VOICES only
        intl_list = ", ".join(f"'{v}'" for v in sorted(INTL_AVAILABLE_VOICES))

        lines.append("-- International-capable voices: set endpoint_modes = [mainland, international]")
        lines.append(f"""UPDATE voice_catalog
SET provider_config = provider_config || '{{"endpoint_modes": ["mainland", "international"]}}'::jsonb,
    updated_at = NOW()
WHERE provider = 'cosyvoice'
  AND voice_id IN ({intl_list});""")
        lines.append("")
        lines.append("-- All other CosyVoice voices: set endpoint_modes = [mainland]")
        lines.append(f"""UPDATE voice_catalog
SET provider_config = provider_config || '{{"endpoint_modes": ["mainland"]}}'::jsonb,
    updated_at = NOW()
WHERE provider = 'cosyvoice'
  AND voice_id NOT IN ({intl_list});""")
    else:
        for vid in ALL_COSYVOICE_VOICE_IDS:
            modes = compute_endpoint_modes(vid)
            modes_json = json.dumps(modes)
            lines.append(
                f"UPDATE voice_catalog "
                f"SET provider_config = provider_config || '{{\"endpoint_modes\": {modes_json}}}'::jsonb, "
                f"updated_at = NOW() "
                f"WHERE voice_id = '{vid}' AND provider = 'cosyvoice';"
            )

    lines.append("")
    lines.append("COMMIT;")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Import CosyVoice endpoint modes")
    parser.add_argument("--sql", action="store_true", help="Generate SQL instead of running DB update")
    args = parser.parse_args()

    if args.sql:
        print(generate_sql())
        return

    # Direct DB update via asyncio + SQLAlchemy
    print("Use --sql to generate SQL for execution in postgres container.")
    print("Example:")
    print("  python gateway/scripts/import_cosyvoice_endpoint_modes.py --sql > /tmp/endpoint_modes.sql")
    print("  docker cp /tmp/endpoint_modes.sql aivideotrans-postgres:/tmp/endpoint_modes.sql")
    print("  docker exec aivideotrans-postgres psql -U avt -d aivideotrans -f /tmp/endpoint_modes.sql")


if __name__ == "__main__":
    main()
