"""Add Studio post-edit infra fields to jobs table.

Revision ID: 015_post_edit_fields
Revises: 014_background_tasks
Create Date: 2026-04-18

Introduces 7 new columns + 4 indexes on ``jobs`` to support the
Studio post-edit workflow (see docs/plans/2026-04-18-studio-post-edit-plan.md):

- display_name       : user-visible friendly title (max 60 chars, fallback to job_id)
- expires_at         : per-job TTL; NULL = legacy rule (created_at + 7d)
- editing_touched_at : last user action in ``editing`` state; idle scanner uses this
- copy_of_job_id     : direct parent of a copy (NULL for originals)
- root_job_id        : copy lineage root; used with user_id for TTL scope (D23)
- edit_generation    : counter of ``editing → running → succeeded`` cycles
- source_content_hash: identifies "same source video" for copy family lookup

Backfill strategy (D41):
- DDL (ADD COLUMN / CREATE INDEX) runs inside the Alembic migration transaction
  as usual — these are fast metadata-only operations on PostgreSQL.
- Data backfill (UPDATE jobs SET ...) runs inside a ``context.autocommit_block()``
  so each batch commits independently. Without autocommit_block, the entire
  ``while True`` loop would run in a single transaction, holding row locks for
  its whole duration regardless of batch size + sleep; sleep would only pause
  the client, not release locks.
- Each 500-row UPDATE grabs row locks only for its own duration (~tens of ms
  on 10k-row tables), then releases before the next batch starts.
- ``root_job_id`` ← ``job_id`` (all existing rows are originals, not copies).
- ``expires_at`` ← ``COALESCE(updated_at, created_at) + 7d`` for non-active jobs.
- Other columns stay NULL (or DEFAULT 0 for edit_generation).

No paid-API calls touched. Phase 0 data-layer migration only — behavioral
changes gated by AIVIDEOTRANS_ENABLE_POST_EDIT in later phases.

Rollback note: downgrade drops columns + indexes. Backfilled data is lost,
but that is intended — root_job_id / expires_at values are deterministic and
can be regenerated by re-running the migration.
"""

from __future__ import annotations

import time

import sqlalchemy as sa
from alembic import context, op

revision = "015_post_edit_fields"
down_revision = "014_background_tasks"
branch_labels = None
depends_on = None


BATCH_SIZE = 500
BATCH_SLEEP_SECONDS = 0.1  # Brief pause between committed batches so concurrent
                            # writers can acquire locks between our UPDATEs.


def upgrade() -> None:
    # --- 1. Add columns (all nullable or with default) ------------------
    op.add_column(
        "jobs",
        sa.Column("display_name", sa.String(length=60), nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column("editing_touched_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column("copy_of_job_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column("root_job_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "edit_generation",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column(
        "jobs",
        sa.Column("source_content_hash", sa.String(length=255), nullable=True),
    )

    # --- 2. Indexes ----------------------------------------------------
    # TTL scope lookup: find the most recent live sibling in a copy family
    # scoped to (root_job_id, user_id). See §5.1 of the post-edit plan.
    op.create_index(
        "idx_jobs_root_user_expires",
        "jobs",
        ["root_job_id", "user_id", "expires_at"],
    )
    op.create_index(
        "idx_jobs_copy_of_job_id",
        "jobs",
        ["copy_of_job_id"],
    )
    # Partial index: only index rows where editing_touched_at IS NOT NULL.
    # idle_scanner queries "status='editing' AND editing_touched_at < cutoff",
    # and the vast majority of jobs never enter editing, so NULL rows don't
    # need index entries.
    op.create_index(
        "idx_jobs_editing_touched_at",
        "jobs",
        ["editing_touched_at"],
        postgresql_where=sa.text("editing_touched_at IS NOT NULL"),
    )
    op.create_index(
        "idx_jobs_source_content_hash",
        "jobs",
        ["source_content_hash"],
    )

    # --- 3. Backfill --------------------------------------------------
    # Alembic's default behaviour is to wrap the whole upgrade() in a single
    # transaction. A naive `while True: UPDATE LIMIT 500` inside that
    # transaction would hold row locks for the full loop duration and sleeps
    # would only pause the client, NOT release locks — which defeats the point
    # of batching. ``autocommit_block()`` temporarily switches the connection
    # to autocommit mode, so each UPDATE commits independently and locks are
    # released between batches.
    #
    # Reference: https://alembic.sqlalchemy.org/en/latest/api/runtime.html
    #   #alembic.runtime.migration.MigrationContext.autocommit_block
    #
    # NOTE: ``op.get_context()`` returns the MigrationContext *instance*.
    # ``from alembic import context`` at the module level is the
    # EnvironmentContext *class*, which doesn't expose ``autocommit_block``.
    # Use ``op.get_context().autocommit_block()`` for the actual API call;
    # the class-level ``context`` is only used for ``is_offline_mode()``
    # below (which IS class-level).

    # Offline / --sql mode cannot execute the while-loop reliably because
    # ``connection.execute()`` returns None when Alembic is just rendering
    # SQL statements, so ``result.rowcount`` would AttributeError. The DDL
    # above has already been emitted — that's what dry-runs actually want
    # to inspect. Online mode (real apply) runs the full backfill below.
    if context.is_offline_mode():
        return

    with op.get_context().autocommit_block():
        connection = op.get_bind()

        # 3a. root_job_id ← job_id for all existing rows (all are originals;
        #     no copy lineage existed before this migration). Each batch
        #     commits via the surrounding autocommit_block.
        while True:
            result = connection.execute(
                sa.text(
                    """
                    UPDATE jobs
                    SET root_job_id = job_id
                    WHERE id IN (
                        SELECT id FROM jobs
                        WHERE root_job_id IS NULL
                        LIMIT :batch_size
                    )
                    """
                ),
                {"batch_size": BATCH_SIZE},
            )
            if result.rowcount == 0:
                break
            # Now that the batch's commit has released row locks, brief pause
            # so concurrent writers have a window to make progress.
            time.sleep(BATCH_SLEEP_SECONDS)

        # 3b. expires_at ← COALESCE(updated_at, created_at) + 7d for non-active
        #     jobs. Active jobs (queued/running) stay NULL; their expires_at
        #     will be written on terminal transition, or fall back to the
        #     legacy rule in cleanup.py for old data.
        while True:
            result = connection.execute(
                sa.text(
                    """
                    UPDATE jobs
                    SET expires_at = COALESCE(updated_at, created_at) + INTERVAL '7 days'
                    WHERE id IN (
                        SELECT id FROM jobs
                        WHERE expires_at IS NULL
                          AND status NOT IN ('queued', 'running')
                        LIMIT :batch_size
                    )
                    """
                ),
                {"batch_size": BATCH_SIZE},
            )
            if result.rowcount == 0:
                break
            time.sleep(BATCH_SLEEP_SECONDS)

    # 3c. display_name is intentionally left NULL here. T0-4 (task naming)
    #     owns the display_name generation algorithm (truncate to 12 CJK chars
    #     etc.) and will backfill on first read or via a dedicated script.
    #     Leaving NULL preserves the "fallback to getJobDisplayTitle" behaviour
    #     during the Phase 0 → T0-4 transition window.


def downgrade() -> None:
    op.drop_index("idx_jobs_source_content_hash", table_name="jobs")
    op.drop_index("idx_jobs_editing_touched_at", table_name="jobs")
    op.drop_index("idx_jobs_copy_of_job_id", table_name="jobs")
    op.drop_index("idx_jobs_root_user_expires", table_name="jobs")
    op.drop_column("jobs", "source_content_hash")
    op.drop_column("jobs", "edit_generation")
    op.drop_column("jobs", "root_job_id")
    op.drop_column("jobs", "copy_of_job_id")
    op.drop_column("jobs", "editing_touched_at")
    op.drop_column("jobs", "expires_at")
    op.drop_column("jobs", "display_name")
